spring:
  data:
    mongodb:
      database: osco
      host: localhost
      port : 27017
#      uri: "mongodb://localhost:27017"

---
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

---
spring:
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 600000
      key-prefix: jdj
    cache-names:
      - product

